name: Use Composite Action from Another Repo

on:
  push:

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use greeting composite action
        uses: your-github-username/greeting-actions/.github/actions/greetings@main
